export const destinations = [
  {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    tagline: "Temple spires and maple canopies above a city built for slow mornings.",
    image: "/images/kyoto.webp",
    duration: "4–6 Days",
    price: 890,
    description:
      "Kyoto rewards the traveler willing to get up before sunrise. We route you between quiet temple courtyards and the old wooden streets of Gion before the tour buses arrive, then leave the afternoons open for the city to happen to you.",
    highlights: [
      "Sunrise visit to Kiyomizu-dera before the crowds",
      "A guided walk through Arashiyama's bamboo groves",
      "Traditional kaiseki dinner in a converted machiya townhouse",
    ],
    itinerary: [
      { day: 1, title: "Arrival & Gion at dusk", detail: "Settle into a traditional ryokan, then walk Higashiyama's lantern-lit streets as evening falls." },
      { day: 2, title: "Temples before the crowds", detail: "Kiyomizu-dera at sunrise, followed by a slow morning through quiet backstreets." },
      { day: 3, title: "Arashiyama & the river", detail: "Bamboo grove at first light, then a boat ride down the Hozugawa River." },
      { day: 4, title: "Departure", detail: "A final morning at leisure before transfer to Kansai Airport." },
    ],
    inclusions: ["3 nights in a traditional ryokan", "Private guide for all listed activities", "Airport transfers", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner (except where noted)", "Travel insurance"],
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    tagline: "Cliffside coves and rice terraces, arranged around the tide.",
    image: "/images/bali.webp",
    duration: "5–7 Days",
    price: 780,
    description:
      "Bali's best beaches are tidal, not scheduled — so we build the route around the water, not a fixed itinerary. Expect early starts for empty coves and long, unplanned afternoons in between.",
    highlights: [
      "Diamond Beach and the eastern cliffs at low tide",
      "A private driver for the full Ubud rice-terrace circuit",
      "One reef-safe snorkeling trip, weather-permitting",
    ],
    itinerary: [
      { day: 1, title: "Arrival & Ubud", detail: "Settle into a rice-field villa, easy evening at leisure." },
      { day: 2, title: "Rice terraces & temples", detail: "Full-day private driver circuit through Ubud's terraces and countryside temples." },
      { day: 3, title: "Diamond Beach at low tide", detail: "Transfer to Nusa Penida for the cliffside coves, timed against the tide charts." },
      { day: 4, title: "Reef snorkeling", detail: "A reef-safe snorkeling trip, weather-permitting, followed by a slow afternoon." },
      { day: 5, title: "Departure", detail: "Morning at leisure before transfer to the airport." },
    ],
    inclusions: ["4 nights (villa + coastal stay)", "Private driver for all excursions", "Airport transfers", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner", "Travel insurance"],
  },
  {
    slug: "srilanka",
    name: "Sri Lanka",
    country: "Ella & the Hill Country",
    tagline: "A blue train, nine stone arches, and tea country in every direction.",
    image: "/images/srilanka.webp",
    duration: "6–8 Days",
    price: 720,
    description:
      "The train from Kandy to Ella is reason enough to visit — we just make sure you get a window seat and time the Nine Arch Bridge crossing for the light. Tea plantation stays fill the rest of the route.",
    highlights: [
      "Reserved window seats on the Kandy–Ella hill train",
      "Nine Arch Bridge timed for late-afternoon light",
      "A working tea estate stay outside Ella",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Kandy", detail: "Settle in, evening visit to the Temple of the Tooth." },
      { day: 2, title: "The hill train to Ella", detail: "A window-seat train ride through tea country, arriving into Ella by afternoon." },
      { day: 3, title: "Nine Arch Bridge & tea estate", detail: "Bridge crossing timed for golden light, overnight at a working tea estate." },
      { day: 4, title: "Little Adam's Peak", detail: "An easy sunrise hike, then a slow day among the plantations." },
      { day: 5, title: "Departure", detail: "Transfer back toward Colombo for onward travel." },
    ],
    inclusions: ["4 nights (Kandy + Ella)", "Reserved hill-train tickets", "Airport transfers", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner", "Travel insurance"],
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    tagline: "Gilded temples and river life, read at street level.",
    image: "/images/bangkok.webp",
    duration: "3–5 Days",
    price: 650,
    description:
      "Bangkok moves fast, so we slow it down — river transfers instead of traffic, a street-food route built with a local guide, and a temple morning timed before the heat sets in.",
    highlights: [
      "Grand Palace and Wat Arun before midday",
      "Chao Phraya river transfers between old and new Bangkok",
      "A night-market food route, not a group tour",
    ],
    itinerary: [
      { day: 1, title: "Arrival & river orientation", detail: "Settle in, evening longtail boat ride along the Chao Phraya." },
      { day: 2, title: "Temples before the heat", detail: "Grand Palace and Wat Arun at opening time, then a riverside lunch." },
      { day: 3, title: "Street food route", detail: "A guided evening food route through Bangkok's night markets." },
      { day: 4, title: "Departure", detail: "Morning at leisure before transfer to the airport." },
    ],
    inclusions: ["3 nights in a riverside hotel", "Private guide for all listed activities", "Airport transfers", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner (except where noted)", "Travel insurance"],
  },
  {
    slug: "maldives",
    name: "Maldives",
    country: "Indian Ocean",
    tagline: "Overwater villas and a horizon with nothing on it.",
    image: "/images/maldives.webp",
    duration: "4–6 Days",
    price: 1650,
    description:
      "The hardest part of the Maldives is the seaplane connection — we time it against your actual flight, not a guess, so the transfer never becomes the story of the trip.",
    highlights: [
      "Seaplane or speedboat transfer arranged door to door",
      "Overwater villa options across a dozen partner resorts",
      "One private sunset cruise included",
    ],
    itinerary: [
      { day: 1, title: "Arrival & seaplane transfer", detail: "Timed seaplane connection straight to your resort, evening at leisure." },
      { day: 2, title: "Reef & lagoon", detail: "A slow day around the house reef, optional snorkeling." },
      { day: 3, title: "Sunset cruise", detail: "A private sunset cruise included as part of the stay." },
      { day: 4, title: "Departure", detail: "Morning at leisure before the return seaplane transfer." },
    ],
    inclusions: ["3 nights in an overwater villa", "Seaplane or speedboat transfers", "One private sunset cruise", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner", "Travel insurance"],
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    tagline: "A skyline and a rainforest, closer together than you'd expect.",
    image: "/images/singapore.webp",
    duration: "3–4 Days",
    price: 820,
    description:
      "Dense, clean, and easy to move through — which is exactly why it works as a stopover or a standalone stay. We build in one slow day between the gardens and the hawker centres.",
    highlights: [
      "Gardens by the Bay routed around the evening light show",
      "Hawker centre orientation on arrival, not day three",
      "Seamless connection if paired with Bangkok or Malaysia",
    ],
    itinerary: [
      { day: 1, title: "Arrival & hawker orientation", detail: "Settle in, evening hawker centre food tour on arrival night." },
      { day: 2, title: "Gardens by the Bay", detail: "Full day at the gardens, timed for the evening light show." },
      { day: 3, title: "Marina Bay & departure", detail: "A relaxed morning around Marina Bay before transfer to the airport." },
    ],
    inclusions: ["2 nights in a central hotel", "Airport transfers", "Gardens by the Bay entry", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner", "Travel insurance"],
  },
  {
    slug: "india",
    name: "India",
    country: "Agra",
    tagline: "Marble domes and a sunrise that's worth the early alarm.",
    image: "/images/india.webp",
    duration: "6–9 Days",
    price: 990,
    description:
      "The Taj Mahal at sunrise is a different building than the Taj Mahal at noon. We arrange entry timing, a private driver, and the paperwork ahead of arrival so the only thing you have to manage is getting up early.",
    highlights: [
      "Sunrise entry timed at the Taj Mahal, before the crowds",
      "Private driver for the Delhi–Agra–Jaipur circuit",
      "Visa paperwork and permits handled ahead of arrival",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Delhi", detail: "Settle in, evening orientation walk through Old Delhi." },
      { day: 2, title: "Transfer to Agra", detail: "Private driver to Agra, afternoon at leisure ahead of an early start." },
      { day: 3, title: "Sunrise at the Taj Mahal", detail: "Timed entry at sunrise, before the crowds, then Agra Fort." },
      { day: 4, title: "On to Jaipur", detail: "Private driver through to Jaipur, the Pink City." },
      { day: 5, title: "Amber Fort & departure", detail: "Morning at Amber Fort before transfer back toward Delhi." },
    ],
    inclusions: ["4 nights (Delhi, Agra, Jaipur)", "Private driver for the full circuit", "Visa paperwork assistance", "Daily breakfast"],
    exclusions: ["International flights", "Lunch & dinner", "Travel insurance"],
  },
];

export function getDestination(slug) {
  return destinations.find((d) => d.slug === slug);
}
